# Generated by Django 5.0.1 on 2024-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDocumentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('processed_data', models.TextField(blank=True, null=True)),
                ('processing_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
